-- MySQL Script generated by MySQL Workbench
-- Wed Dec 11 19:10:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Database diner
-- -----------------------------------------------------
CREATE DATABASE  IF NOT EXISTS `diner`;
USE `diner`;

DROP TABLE IF EXISTS `Daily` ;
DROP TABLE IF EXISTS `Food_picked` ;
DROP TABLE IF EXISTS `Meals` ;
DROP TABLE IF EXISTS `Food` ;
DROP TABLE IF EXISTS `Menu` ;
DROP TABLE IF EXISTS `Restaurant` ;
DROP TABLE IF EXISTS `Client` ;
DROP TABLE IF EXISTS `User` ;


-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `User` (
  `user_id` CHAR(21) NOT NULL UNIQUE,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL UNIQUE,
  `calories` INT NULL,
  `carbs` INT NULL,
  `fat` INT NULL,
  `protein` INT NULL,
  `type` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Client`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Client` (
  `client_id` CHAR(21) NOT NULL,
  `nutr_id` CHAR(21) NOT NULL,
  FOREIGN KEY (`client_id`)
    REFERENCES `User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (`nutr_id`)
    REFERENCES `User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    PRIMARY KEY (`nutr_id`, `client_id`)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Restaurant` (
  `rest_name` VARCHAR(45) NOT NULL,
  `rest_email` VARCHAR(45) NOT NULL UNIQUE,
  `rest_password` VARCHAR(45) NOT NULL,
  `location_lat` DOUBLE NULL,
  `location_long` DOUBLE NULL,
  PRIMARY KEY (`rest_email`)
)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `Food`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Food` (
  `rest_email` VARCHAR(45) NOT NULL,
  `food_name` VARCHAR(45) NOT NULL,
  `calories` INT NOT NULL,
  `carb_val` INT NOT NULL,
  `prot_val` INT NOT NULL,
  `fat_val` INT NOT NULL,
  `price` DOUBLE NULL,
  `type` INT NOT NULL,
  CONSTRAINT `mn_id`
  FOREIGN KEY (rest_email)
    REFERENCES `Restaurant` (rest_email)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    PRIMARY KEY (`rest_email`, `food_name`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Meals`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Meals` (
  `user_id` CHAR(21) NOT NULL,
  `meal_name` VARCHAR(45) NOT NULL,
  `calories` INT NOT NULL,
  `carbs` INT NOT NULL,
  `fat` INT NOT NULL,
  `protein` INT NOT NULL,
  FOREIGN KEY (`user_id`)
    REFERENCES `User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    PRIMARY KEY (`user_id`, `meal_name`)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Daily`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Daily` (
  `user_id` CHAR(21) NOT NULL,
  `calories` INT NOT NULL DEFAULT 0,
  `carbs` INT NOT NULL DEFAULT 0,
  `fat` INT NOT NULL DEFAULT 0,
  `protein` INT NOT NULL DEFAULT 0,
  `daily_date` DATE NOT NULL,
  FOREIGN KEY (`user_id`)
    REFERENCES `User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Food_picked`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Food_picked` (
  `time` DATETIME NOT NULL,
  `food_name` VARCHAR(45) NOT NULL,
  `rest_email` VARCHAR(45) NOT NULL,
  `picked_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` CHAR(21) NOT NULL,
  FOREIGN KEY (`user_id`)
    REFERENCES `User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  FOREIGN KEY ( `rest_email`, `food_name`)
    REFERENCES `Food` (`rest_email`, `food_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    PRIMARY KEY (`picked_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
